export { default as Logo } from "./features/Logo.jpg"
export { default as LogoDark } from "./features/Logo-dark.jpg"
export { default as searchBg } from "./features/search-bg.webp"
export { default as cover } from "./features/cover.png"
export { default as coverX2 } from "./features/coverX2.png"
export { default as hotel } from "./features/hotel.jpg"
